import { RoomStatus, RoomType } from "@/hooks/types";

export const MOCK_ROOMS = [
  { id: "1", number: "101", type: RoomType.SINGLE, status: RoomStatus.AVAILABLE, price: 120, floor: 1 },
  {
    id: "2",
    number: "102",
    type: RoomType.SINGLE,
    status: RoomStatus.OCCUPIED,
    price: 120,
    floor: 1,
    guest: { name: "Alex Johnson", checkIn: "2023-10-24", checkOut: "2023-10-27", nights: 3 },
  },
  { id: "3", number: "103", type: RoomType.DOUBLE, status: RoomStatus.AVAILABLE, price: 200, floor: 1 },
  {
    id: "4",
    number: "104",
    type: RoomType.DOUBLE,
    status: RoomStatus.OCCUPIED,
    price: 200,
    floor: 1,
    guest: { name: "Sarah Miller", checkIn: "2023-10-20", checkOut: "2023-10-25", nights: 5 },
  },
  { id: "5", number: "105", type: RoomType.SUITE, status: RoomStatus.MAINTENANCE, price: 450, floor: 1 },
  { id: "6", number: "201", type: RoomType.DELUXE, status: RoomStatus.AVAILABLE, price: 350, floor: 2 },
  {
    id: "7",
    number: "202",
    type: RoomType.DELUXE,
    status: RoomStatus.OCCUPIED,
    price: 350,
    floor: 2,
    guest: { name: "Michael Brown", checkIn: "2023-10-22", checkOut: "2023-10-26", nights: 4 },
  },
  { id: "8", number: "203", type: RoomType.DOUBLE, status: RoomStatus.MAINTENANCE, price: 200, floor: 2 },
  { id: "9", number: "204", type: RoomType.DOUBLE, status: RoomStatus.AVAILABLE, price: 200, floor: 2 },
  {
    id: "10",
    number: "205",
    type: RoomType.SUITE,
    status: RoomStatus.OCCUPIED,
    price: 450,
    floor: 2,
    guest: { name: "Emma Watson", checkIn: "2023-10-18", checkOut: "2023-10-28", nights: 10 },
  },
  { id: "11", number: "301", type: RoomType.SINGLE, status: RoomStatus.AVAILABLE, price: 120, floor: 3 },
  { id: "12", number: "302", type: RoomType.DOUBLE, status: RoomStatus.AVAILABLE, price: 200, floor: 3 },
  {
    id: "13",
    number: "303",
    type: RoomType.DELUXE,
    status: RoomStatus.OCCUPIED,
    price: 350,
    floor: 3,
    guest: { name: "David Wilson", checkIn: "2023-10-25", checkOut: "2023-10-30", nights: 5 },
  },
  { id: "14", number: "304", type: RoomType.SUITE, status: RoomStatus.AVAILABLE, price: 450, floor: 3 },
  { id: "15", number: "305", type: RoomType.SINGLE, status: RoomStatus.AVAILABLE, price: 120, floor: 3 },
  {
    id: "16",
    number: "401",
    type: RoomType.SUITE,
    status: RoomStatus.OCCUPIED,
    price: 600,
    floor: 4,
    guest: { name: "Sophia Chen", checkIn: "2023-10-23", checkOut: "2023-10-26", nights: 3 },
  },
  { id: "17", number: "402", type: RoomType.DELUXE, status: RoomStatus.AVAILABLE, price: 380, floor: 4 },
  { id: "18", number: "403", type: RoomType.DOUBLE, status: RoomStatus.AVAILABLE, price: 210, floor: 4 },
];
